list/urls.py
from django.urls import path

from list.views import (
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskCompletedView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TagListView,
    TaskUpdateView

)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
     path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tasks/<int:pk>/complete/",
        TaskCompletedView.as_view(),
        name="task-complete",
    ),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
]
app_name = "list"

todo_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("list.urls", namespace="list")),
]

list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    start_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True)
    is_completed = models.BooleanField(default=False)
    TASK_PRIORITY_CHOICE = (
        ("Urgent", "Urgent"),
        ("High", "High"),
        ("Normal", "Normal"),
        ("Low", "Low"),
    )
    priority = models.CharField(
        max_length=20,
        choices=TASK_PRIORITY_CHOICE,
        default="Normal",
    )
    tags = models.ManyToManyField(Tag, related_name="tags")

list/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View, generic

from list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "task_list.html"
    ordering = ["is_completed", "-start_time"]
    paginate_by = 2


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("list:task-list")


class TaskCompletedView(View):
    model = Task

    def post(self, request, **kwargs) -> HttpResponse:
        task = Task.objects.get(id=kwargs["pk"])
        task.is_completed = not task.is_completed
        task.save()
        return redirect("list:task-list")



class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Taxi Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
   <li class="list-group-item"><a href="{% url 'list:task-list' %}">Home</a></li>
   <li class="list-group-item"><a href="{% url 'list:tag-list' %}">Tags</a></li>
</ul>

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tag List</h1>
  <a href="{% url 'list:tag-create' %}" class="btn btn-primary">Add Tag</a>
  {% if tag_list %}
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td>
        <a href="{% url 'list:tag-update' pk=tag.id %}">
          Update
        </a>
      </td>
      <td>
        <a style="color: red"
          href="{% url 'list:tag-delete' pk=tag.id %}">
          Delete
        </a>
      </td>
    </tr>
    {% endfor %}

  </table>
  {% else %}
    <p>There are no tags yet.</p>
  {% endif %}
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}
{% block content %}
  <h1>
    TODO list
    <a href="{% url 'list:task-create' %}" style="float: right" class="btn btn-primary link-to-page">
      New task
    </a>
  </h1>
  {% if task_list %}
    <ul>
      {% for task in task_list %}
        {% comment %} <li>
          <a href="{% url "taxi:car-detail" pk=car.id %} ">{{ car.id }}</a>
          {{ car.model }} ({{ car.manufacturer.name }})
        </li> {% endcomment %}
        <div class="card">
          
            <h4 class="card-header">{{ task.name }}</h4>
          <div display: inline>
            <span class="badge badge-info">Priority: {{ task.priority }} </span>
            {% if  task.is_completed %}
              <span class="badge badge-success">DONE</span>
              <form action="{% url 'list:task-complete' pk=task.id %}" method="post" novalidate>
                {% csrf_token %}
                <input type="hidden" name="is_completed" value="False">
                <input type="submit" value="Undo" class="btn btn-secondary">
              </form>
            {% else %}
              <span class="badge badge-danger">NOT DONE</span>
              <form action="{% url 'list:task-complete' pk=task.id %}" method="post" novalidate>
                {% csrf_token %}
                <input type="hidden" name="is_completed" value="True">
                <input type="submit" value="Complete" class="btn btn-success">
              </form>
            {% endif %}
          </div>
          
          <div class="card-body">
            <h5 class="card-title">{{ task.description}}</h5>
            <p class="card-text">Created: {{ task.start_time }} 
              {% if   task.is_completed %}
              <span class="badge badge-secondary">DEADLINE: {{ task.deadline }} </span></p>
              {% else %}
              <span class="badge badge-danger">DEADLINE: {{ task.deadline }} </span></p>
              {% endif %} 
            <a href="{% url 'list:task-update' pk=task.id %}" class="btn btn-primary">Update</a> <a href="{% url 'list:task-delete' pk=task.id %}" class="btn btn-primary">Delete</a>
            <h5 class="card-title">Tags: {% for tag in task.tags.all %} {{ tag }}, {% endfor %} </h5>
          </div>
        </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks yet</p>
  {% endif %}
{% endblock %}